name: "Neo push tests"

on:
  workflow_call:

jobs:
  neo-push-tests:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/password
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Run neo-push tests
        run: yarn --cwd examples/neo-push/server run test
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: password
          NEO_URL: bolt://localhost:7687